server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  profiles:
    include: oauth

  datasource:
    url: jdbc:mysql://studit.cp0whbx3cm7f.ap-northeast-2.rds.amazonaws.com:3306/chalkak?serverTimezone=Asia/Seoul
#    url: jdbc:mysql://localhost:3306/feelim?serverTimezone=Asia/Seoul
    username: root
    password: minamina
#    password: 8244
    driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true

  thymeleaf:
    enabled: false

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
  com.amazonaws.util.EC2MetadataUtils: error

jwt:
  secret: 'feelim'
  access-expired: 18000 #30(분) - 단위 (초)

firebase:
  project-id: chalkak-dd249
  key-path: firebase/chalkak_service_key.json