spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            #client-id == REST api KEY
            client-id: 3383a153d79fbb4075a916ac3c642dc2
            client-secret: WpfHf9q7u6LckFpzHy50sN8o0xDNY4Cx
            redirect-uri: "https://chalkak.shop/{action}/oauth2/code/{registrationId}"
#            redirect-uri: "http://localhost:8080/{action}/oauth2/code/{registrationId}"
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, account_email
            client-name: Kakao

          naver:
            client-id: 8PJ8Q77tTqjFcYTCLVJd
            client-secret: 0AACMw6ffm
            redirect-uri: "http://localhost:8080/{action}/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope: name,email,nickname,gender,birthday, birthyear, mobile
            client-name: Naver


        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response